# [build]
#   publish = "exampleSite/public"
#   command = "cd exampleSite && hugo --gc --themesDir ../.."
  
# [build.environment]
#   HUGO_VERSION = "0.73.0"
#   HUGO_THEME = "repo"
#   HUGO_BASEURL = "/"
[build]
  publish = "EXTREM-ELECTRIC/public"
  command = "cd EXTREM-ELECTRIC && hugo --gc --themesDir ../.."
  
[build.environment]
  HUGO_VERSION = "0.73.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"