[build]
  publish = "vex/exampleSite/public"
  command = "cd vex/exampleSite && hugo --gc --themesDir ../.."
  
[build.environment]
  HUGO_VERSION = "0.73.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"
